[files]
extend-exclude = [
  "atcoder/**",
  "multiplicative-function/enamurate-multiplicative-function.hpp",
  "segment-tree/li-chao-tree-abstruct.hpp",
  "shortest-path/dijkstra-abstruct.hpp",
  "typos.toml",
]

[default.extend-identifiers]
ArbitaryLCP = "ArbitaryLCP"
dijkstra_abstruct = "dijkstra_abstruct"
enamurate_multiplicative_function = "enamurate_multiplicative_function"
exp_enamurate = "exp_enamurate"
NumberTheroemTransform = "NumberTheroemTransform"
Padd = "Padd"
Stirling2nd = "Stirling2nd"
Stirling2ndRow = "Stirling2ndRow"

[default.extend-words]
abstruct = "abstract"
BA = "BA"
ba = "ba"
choise = "choice"
cll = "c_ll"
enamurate = "enumerate"
fim = "f_im"
fo = "first_occurrence"
fre = "f_re"
Millar = "Miller"
Nimber = "Nimber"
nimber = "nimber"
numer = "numerator"
precedessor = "predecessor"
procedessor = "predecessor"
ths = "target_hash"
thr = "threshold"
Toom = "Toom"
toom = "toom"
